/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    BooleanSetting: typeof import('./src/components/interfaces/settings/BooleanSetting.vue')['default']
    ButtonSetting: typeof import('./src/components/interfaces/settings/ButtonSetting.vue')['default']
    Camera: typeof import('./src/components/interfaces/Camera.vue')['default']
    ChoiceStrig: typeof import('./src/components/interfaces/settings/ChoiceStrig.vue')['default']
    ChoiceString: typeof import('./src/components/interfaces/settings/ChoiceString.vue')['default']
    copy: typeof import('./src/components/interfaces/settings/StringSetting copy.vue')['default']
    Device: typeof import('./src/components/Device.vue')['default']
    DeviceList: typeof import('./src/components/DeviceList.vue')['default']
    DeviceProvider: typeof import('./src/components/interfaces/DeviceProvider.vue')['default']
    DeviceSetting: typeof import('./src/components/interfaces/settings/DeviceSetting.vue')['default']
    DeviceSettings: typeof import('./src/components/DeviceSettings.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    FilteredDeviceList: typeof import('./src/components/FilteredDeviceList.vue')['default']
    InlineTextField: typeof import('./src/components/InlineTextField.vue')['default']
    InstallPlugin: typeof import('./src/components/plugin/InstallPlugin.vue')['default']
    InstallPluginCard: typeof import('./src/components/plugin/InstallPluginCard.vue')['default']
    Launcher: typeof import('./src/components/Launcher.vue')['default']
    MultipleString: typeof import('./src/components/interfaces/settings/MultipleString.vue')['default']
    Plugins: typeof import('./src/components/plugin/Plugins.vue')['default']
    PtyComponent: typeof import('./src/components/PtyComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/interfaces/settings/Settings.vue')['default']
    StringSetting: typeof import('./src/components/interfaces/settings/StringSetting.vue')['default']
    StringSettings: typeof import('./src/components/interfaces/settings/StringSettings.vue')['default']
    Terminal: typeof import('./src/components/Terminal.vue')['default']
    ToolbarTooltipButton: typeof import('./src/components/ToolbarTooltipButton.vue')['default']
  }
}
