/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    BooleanSetting: typeof import('./src/components/interfaces/settings/BooleanSetting.vue')['default']
    ButtonSetting: typeof import('./src/components/interfaces/settings/ButtonSetting.vue')['default']
    Camera: typeof import('./src/components/interfaces/Camera.vue')['default']
    ChoiceStringSetting: typeof import('./src/components/interfaces/settings/ChoiceStringSetting.vue')['default']
    ClipPathEditor: typeof import('./src/components/ClipPathEditor.vue')['default']
    ClipPathSetting: typeof import('./src/components/interfaces/settings/ClipPathSetting.vue')['default']
    DateTimeSetting: typeof import('./src/components/interfaces/settings/DateTimeSetting.vue')['default']
    DaySetting: typeof import('./src/components/interfaces/settings/DaySetting.vue')['default']
    DeleteDeviceDialog: typeof import('./src/components/DeleteDeviceDialog.vue')['default']
    Device: typeof import('./src/components/Device.vue')['default']
    DeviceCreator: typeof import('./src/components/interfaces/DeviceCreator.vue')['default']
    DeviceInterfaceSetting: typeof import('./src/components/interfaces/settings/DeviceInterfaceSetting.vue')['default']
    DeviceList: typeof import('./src/components/DeviceList.vue')['default']
    DeviceProvider: typeof import('./src/components/interfaces/DeviceProvider.vue')['default']
    DeviceSetting: typeof import('./src/components/interfaces/settings/DeviceSetting.vue')['default']
    DeviceSettings: typeof import('./src/components/DeviceSettings.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    Extensions: typeof import('./src/components/interfaces/settings/Extensions.vue')['default']
    FilteredDeviceList: typeof import('./src/components/FilteredDeviceList.vue')['default']
    HtmlSetting: typeof import('./src/components/interfaces/settings/HtmlSetting.vue')['default']
    InlineTextField: typeof import('./src/components/InlineTextField.vue')['default']
    InstallPlugin: typeof import('./src/components/plugin/InstallPlugin.vue')['default']
    InstallPluginCard: typeof import('./src/components/plugin/InstallPluginCard.vue')['default']
    Launcher: typeof import('./src/components/Launcher.vue')['default']
    MixinProvider: typeof import('./src/components/interfaces/MixinProvider.vue')['default']
    ObjectDetector: typeof import('./src/components/interfaces/ObjectDetector.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Plugins: typeof import('./src/components/plugin/Plugins.vue')['default']
    PtyComponent: typeof import('./src/components/PtyComponent.vue')['default']
    Readme: typeof import('./src/components/interfaces/Readme.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RTCSignalingChannel: typeof import('./src/components/interfaces/RTCSignalingChannel.vue')['default']
    Scriptable: typeof import('./src/components/interfaces/Scriptable.vue')['default']
    ScriptSetting: typeof import('./src/components/interfaces/settings/ScriptSetting.vue')['default']
    ScryptedCoreDeviceShortcut: typeof import('./src/components/ScryptedCoreDeviceShortcut.vue')['default']
    ScryptedLogger: typeof import('./src/components/interfaces/ScryptedLogger.vue')['default']
    ScryptedPlugin: typeof import('./src/components/interfaces/ScryptedPlugin.vue')['default']
    ScryptedSettings: typeof import('./src/components/ScryptedSettings.vue')['default']
    Settings: typeof import('./src/components/interfaces/settings/Settings.vue')['default']
    SplatSetting: typeof import('./src/components/interfaces/settings/SplatSetting.vue')['default']
    StringSetting: typeof import('./src/components/interfaces/settings/StringSetting.vue')['default']
    Terminal: typeof import('./src/components/Terminal.vue')['default']
    ToolbarTooltipButton: typeof import('./src/components/ToolbarTooltipButton.vue')['default']
    Users: typeof import('./src/components/Users.vue')['default']
  }
}
